<a href="https://colab.research.google.com/github/fabiomungo/ecampus/blob/main/02_tf_matrix_multiplication.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Moltiplicazione di matrici con TensorFlow (tf.matmul)

> - Istruttore: prof. Fabio Mungo - eCampus Master AI Engineering

## MatMul base: (m×n) @ (n×p) -> (m×p)

try...except Exception as e:: Questo è un blocco di gestione delle eccezioni. Significa che il codice all'interno del blocco try verrà eseguito e, se si verifica un errore (un'eccezione), l'esecuzione passerà al blocco except. Questo è utile per gestire situazioni come TensorFlow che non è installato o configurato correttamente.

import tensorflow as tf: Questa riga importa la libreria TensorFlow, che è un framework open-source ampiamente utilizzato per il machine learning e il deep learning. Viene importata con l'alias tf per rendere il suo utilizzo più conciso nel codice.

A = tf.random.normal((2,3)): Qui viene creato un tensore (che è l'equivalente di una matrice o un array multidimensionale in TensorFlow) chiamato A.:

tf.random.normal(): Questa funzione genera numeri casuali da una distribuzione normale (gaussiana) con media 0 e deviazione standard 1.
(2,3): Questo specifica la forma del tensore, il che significa che A sarà una matrice con 2 righe e 3 colonne.
B = tf.random.normal((3,4)): Allo stesso modo, viene creato un secondo tensore chiamato B con numeri casuali da una distribuzione normale. B avrà una forma di (3,4), ovvero 3 righe e 4 colonne.

C = tf.matmul(A,B): Questa è l'operazione centrale: la moltiplicazione di matrici. tf.matmul() esegue il prodotto matriciale standard tra A e B.

Compatibilità: Per eseguire la moltiplicazione matriciale A @ B, il numero di colonne della matrice A deve essere uguale al numero di righe della matrice B.
Nel nostro caso, A ha forma (2, 3) e B ha forma (3, 4). Poiché 3 == 3, le matrici sono compatibili per la moltiplicazione.
Forma del risultato: La matrice risultante C avrà un numero di righe uguale a quello di A e un numero di colonne uguale a quello di B.
Quindi, C avrà forma (2, 4).
print('A', A.shape, 'B', B.shape, 'C', C.shape): Questa riga stampa le forme (dimensioni) dei tre tensori: A, B e C. Questo è utile per verificare che la moltiplicazione matriciale sia avvenuta correttamente e che il tensore risultante C abbia la forma prevista (2,4).

print('TF non disponibile:', e): Se TensorFlow non è installato o se si verifica un altro errore durante l'esecuzione del codice nel blocco try, questo messaggio verrà stampato, mostrando la causa dell'errore.

In [ ]:
try:
 import tensorflow as tf
 A=tf.random.uniform((2,3), minval=0, maxval=10, dtype=tf.int32)
 B=tf.random.uniform((3,4), minval=0, maxval=10, dtype=tf.int32)
 C=tf.matmul(A,B)
 print('A=',A,"\n",'B=',B,"\n"'C=',C)
 print('A',A.shape,'B',B.shape,'C',C.shape)
except Exception as e:
 print('TF non disponibile:', e)

## Batch matmul: (batch,m,n) @ (batch,n,p)

questo codice dimostra la moltiplicazione di matrici batch (batch matmul) utilizzando TensorFlow. È simile all'esempio precedente, ma opera su più matrici contemporaneamente.

In [ ]:
try:
 import tensorflow as tf
 A=tf.random.normal((5,2,3))
 B=tf.random.normal((5,3,4))
 C=tf.matmul(A,B)
 print(C.shape)
except Exception as e:
 print('TF non disponibile:', e)

## Esercizio: matmul manuale in numpy

questo codice Python implementa manualmente la moltiplicazione di matrici usando NumPy e poi ne verifica la correttezza confrontandola con l'operatore di moltiplicazione matriciale integrato di NumPy.

**matmul_manual**: Dettaglia la logica interna della funzione matmul_manual, inclusa l'inizializzazione, il controllo delle dimensioni e i cicli annidati per il calcolo del prodotto.

**Creazione di matrici di test**: Spiega come vengono create le matrici A e B di esempio per testare la funzione.

**Confronto e verifica**: Descrivi l'ultima riga di codice che confronta il risultato della funzione manuale con il prodotto matriciale di NumPy e stampa la massima differenza.

**Contesto e utilità**: Fornisci il contesto sull'utilità di questa implementazione manuale per comprendere i principi del deep learning.

In [ ]:
import numpy as np

def matmul_manual(A,B):
 A=np.asarray(A); B=np.asarray(B)
 m,n=A.shape
 n2,p=B.shape
 assert n==n2
 C=np.zeros((m,p))
 for i in range(m):
  for j in range(p):
   C[i,j]=(A[i,:]*B[:,j]).sum()
 return C

A=np.random.randn(2,3)
B=np.random.randn(3,4)
print(np.max(np.abs(matmul_manual(A,B)-(A@B))))

# Task
add_text_cell(content='## Introduzione alle Operazioni Fondamentali nel Deep Learning')

## Introduzione Operazioni Deep Learning

### Subtask:
Aggiungi una cella di testo per introdurre la nuova sezione dedicata alle operazioni fondamentali nel Deep Learning.


## Introduzione alle Operazioni Fondamentali nel Deep Learning

## Operazioni Matrice PyTorch

### Subtask:
Aggiungi una cella di codice che dimostra operazioni di base sulle matrici in PyTorch, inclusa la moltiplicazione (`torch.matmul`) e operazioni elemento per elemento, anche con broadcasting.


il codice nella cella sottostante dimostra diverse operazioni fondamentali sui tensori in PyTorch, inclusa la moltiplicazione di matrici, operazioni elemento per elemento e il broadcasting. Ecco una spiegazione dettagliata:

1) Importazione della libreria PyTorch: Spiegazione della riga che importa la libreria torch.

2) Creazione di tensori di esempio per la moltiplicazione di matrici: Dettagli sulla creazione di tensor_a e tensor_b con torch.randn e le loro forme.

3) Esecuzione della moltiplicazione di matrici (torch.matmul): Spiegazione di come torch.matmul esegue il prodotto matriciale, inclusa la compatibilità delle dimensioni e la forma del risultato.

4) Creazione di tensori di esempio per operazioni elemento per elemento: Dettagli sulla creazione di tensor_c e tensor_d con torch.randn.

5) Esecuzione della moltiplicazione elemento per elemento: Spiegazione dell'operazione * per la moltiplicazione elemento per elemento tra tensori.

6) Dimostrazione del Broadcasting con uno scalare: Spiegazione di come un tensore viene moltiplicato per uno scalare, estendendo implicitamente lo scalare a tutte le dimensioni del tensore.

7) Dimostrazione del Broadcasting con un tensore: Spiegazione di un esempio più complesso di broadcasting, dove un tensore di dimensione (1,3) viene esteso per essere compatibile con un tensore (2,3) durante la moltiplicazione.

8) Output delle forme dei tensori: Spiegazione dell'uso di print e .shape per visualizzare i tensori e le loro dimensioni in ogni passaggio.


**Reasoning**:
To fulfill the subtask, I need to add a code cell that demonstrates basic PyTorch matrix operations, including matrix multiplication, element-wise operations, and broadcasting, as specified in the instructions.



In [ ]:
import torch

# 2. Crea due tensori di esempio
tensor_a = torch.randn(2, 3) # Dimensione (2, 3)
tensor_b = torch.randn(3, 4) # Dimensione (3, 4)

print("Tensor A:\n", tensor_a)
print("Tensor B:\n", tensor_b)

# 3. Esegui la moltiplicazione di matrici usando torch.matmul()
matrix_product = torch.matmul(tensor_a, tensor_b)
print("\nMatrix Multiplication (torch.matmul) A @ B:\n", matrix_product)
print("Shape of matrix_product:", matrix_product.shape)

# 4. Crea altri due tensori per l'operazione elemento per elemento
tensor_c = torch.randn(2, 3)
tensor_d = torch.randn(2, 3)

print("\nTensor C:\n", tensor_c)
print("Tensor D:\n", tensor_d)

# 5. Esegui la moltiplicazione elemento per elemento
elementwise_product = tensor_c * tensor_d
print("\nElement-wise Multiplication C * D:\n", elementwise_product)

# 6. Dimostra il broadcasting
# Moltiplicazione per uno scalare
scalar = 5.0
broadcast_scalar = tensor_c * scalar
print("\nBroadcasting with a scalar (Tensor C * scalar):\n", broadcast_scalar)

# Moltiplicazione con un tensore di dimensione (1, 3)
tensor_e = torch.randn(1, 3) # Questo tensore verrà "broadcastato" sulla prima dimensione
broadcast_tensor = tensor_c * tensor_e
print("\nBroadcasting with a (1,3) tensor (Tensor C * Tensor E):\n", broadcast_tensor)
print("Shape of broadcast_tensor:", broadcast_tensor.shape)

## Reshaping e Trasposizione PyTorch

### Subtask:
Aggiungi una cella di codice per mostrare come rimodellare (`reshape`) e trasporre (`transpose` o `.T`) tensori in PyTorch.


questo codice dimostra come rimodellare e trasporre tensori in PyTorch. Vediamo i dettagli:

Importazione della libreria PyTorch: Spiegazione della riga che importa la libreria torch.

1) Creazione del tensore originale: Dettagli sulla creazione di tensor_original con torch.randn e la sua forma iniziale (2,3).
2) Rimodellamento del tensore (reshape): Spiegazione delle due operazioni di reshape: una da (2,3) a (3,2) e l'altra da (2,3) a (6,). Verrà illustrato l'uso di .reshape() e torch.reshape().
3) Trasposizione del tensore (transpose): Spiegazione delle due operazioni di trasposizione: usando la proprietà .T e la funzione torch.transpose(), dimostrando come scambiare le dimensioni del tensore (da (2,3) a (3,2)).

4) Output e forme dei tensori: Spiegazione dell'uso di print per visualizzare i tensori risultanti e le loro dimensioni (.shape) in ogni passaggio.

**Reasoning**:
To demonstrate reshaping and transposing tensors in PyTorch, I need to add a code cell that imports torch, creates a sample tensor, then applies reshape and transpose operations, printing the tensor and its shape at each significant step as per the instructions.



In [ ]:
import torch

# 2. Crea un tensore PyTorch di esempio
tensor_original = torch.randn(2, 3)

# 3. Stampa il tensore originale e la sua forma
print("Tensore Originale:\n", tensor_original)
print("Forma del Tensore Originale:", tensor_original.shape)

# 4. Rimodella il tensore in una nuova forma compatibile
# Esempio 1: da (2,3) a (3,2)
tensor_reshaped_1 = tensor_original.reshape(3, 2)
print("\nTensore Rimodellato (3,2):\n", tensor_reshaped_1)
print("Forma del Tensore Rimodellato (3,2):", tensor_reshaped_1.shape)

# Esempio 2: da (2,3) a (6,)
tensor_reshaped_2 = torch.reshape(tensor_original, (6,))
print("\nTensore Rimodellato (6,):\n", tensor_reshaped_2)
print("Forma del Tensore Rimodellato (6,):", tensor_reshaped_2.shape)

# 6. Trasponi il tensore originale
# Usando .T
tensor_transposed_T = tensor_original.T
print("\nTensore Trasposto (.T):\n", tensor_transposed_T)
print("Forma del Tensore Trasposto (.T):", tensor_transposed_T.shape)

# Usando torch.transpose()
tensor_transposed_func = torch.transpose(tensor_original, 0, 1)
print("\nTensore Trasposto (torch.transpose):\n", tensor_transposed_func)
print("Forma del Tensore Trasposto (torch.transpose):", tensor_transposed_func.shape)

## Esempio Forward Propagation PyTorch

### Subtask:
Crea una cella di codice con un semplice esempio di forward propagation per un layer lineare con funzione di attivazione (es. ReLU o Sigmoid) in PyTorch.


Questo codice crea un semplice esempio di forward propagation (propagazione in avanti) in PyTorch. Questo è un concetto fondamentale nelle reti neurali, dove i dati di input vengono elaborati attraverso i diversi strati del modello per produrre un output. Ecco una spiegazione dettagliata delle diverse sezioni del codice:

1) Importazione delle librerie: Spiegazione delle righe che importano torch e torch.nn, necessarie per la creazione e la gestione dei tensori e dei moduli di rete neurale in PyTorch.

2) Definizione del Layer Lineare: Dettagli sulla creazione di un layer lineare (nn.Linear) con un numero specifico di features di input e output. Questo layer esegue una trasformazione lineare (moltiplicazione matriciale e aggiunta di un bias).

3) Definizione della Funzione di Attivazione: Spiegazione della scelta e della creazione di una funzione di attivazione ReLU (nn.ReLU), che introduce non-linearità nel modello.

4) Creazione del Tensore di Input: Dettagli sulla creazione di un tensore di input di esempio (input_tensor) con torch.randn, specificando la sua forma (dimensione del batch e numero di features).

5) Esecuzione della Forward Propagation: Spiegazione dei passaggi sequenziali dell'input attraverso il layer lineare e successivamente attraverso la funzione di attivazione, inclusa l'osservazione delle forme dei tensori intermedi e finali.

6) Output dei tensori e delle forme: Spiegazione dell'uso di print e .shape per visualizzare i tensori e le loro dimensioni in ogni passaggio chiave del processo di forward propagation.

**Reasoning**:
To demonstrate forward propagation in PyTorch, I need to add a code cell that sets up a linear layer, an activation function, an input tensor, and then performs the forward pass, printing the intermediate and final outputs along with their shapes.



In [ ]:
import torch
import torch.nn as nn

# 1. Definisci un layer lineare
input_features = 10
output_features = 5
linear_layer = nn.Linear(input_features, output_features)
print(f"Layer Lineare: {linear_layer}\n")

# 2. Definisci una funzione di attivazione (es. ReLU)
activation_function = nn.ReLU()
print(f"Funzione di Attivazione: {activation_function}\n")

# 3. Crea un tensore di input di esempio
# Batch di 1 elemento con 10 features
input_tensor = torch.randn(1, input_features)
print(f"Tensore di Input:\n{input_tensor}\nShape: {input_tensor.shape}\n")

# 4. Esegui la forward propagation
# Passaggio attraverso il layer lineare
output_linear = linear_layer(input_tensor)
print(f"Output dopo il Layer Lineare:\n{output_linear}\nShape: {output_linear.shape}\n")

# Passaggio attraverso la funzione di attivazione
output_activated = activation_function(output_linear)
print(f"Output dopo la Funzione di Attivazione (ReLU):\n{output_activated}\nShape: {output_activated.shape}\n")

## Visualizzazione della Forward Propagation in una Rete Neurale Semplice

La forward propagation (o propagazione in avanti) è il processo attraverso il quale un input viene elaborato da una rete neurale per produrre un output. In questa sezione, vedremo un esempio dettagliato di come i dati fluiscono attraverso un singolo strato neurale, includendo la moltiplicazione per i pesi, l'aggiunta del bias e l'applicazione di una funzione di attivazione. Questo aiuterà a visualizzare il "viaggio" dei dati attraverso la rete.


## Rappresentazione Schematica della Forward Propagation

Procediamo con una descrizione più dettagliata e una rappresentazione schematica (in testo) di come i dati fluiscono attraverso i layer della nostra semplice rete neurale, basandoci sull'esempio numerico appena visto.

### 1. Input Layer (dati di ingresso)

I dati iniziano come un tensore di input. Nel nostro esempio, `input_data` è `[[1.0, 2.0]]`. Questo rappresenta un singolo esempio (batch size = 1) con due caratteristiche (features).

```
Input Layer (x)
  [1.0, 2.0] --(2 features)
```

### 2. Linear Transformation (Moltiplicazione per i Pesi e Aggiunta del Bias)

L'input viene poi moltiplicato per la matrice dei pesi (`W`) e viene aggiunto il vettore di bias (`b`). Questo costituisce la trasformazione lineare del layer denso.

#### Dettaglio:
*   **Pesi (W):** `[[1.0, 0.0, 2.0], [1.0, 3.0, 0.0]]` (Forma: 2x3)
*   **Bias (b):** `[0.0, 1.0, 0.0]` (Forma: 3)

Il calcolo è: `z = x @ W + b`

#### Flusso:

```
Input (x)
 [1.0, 2.0]
      |
      V
Layer Lineare (Wx + b = z)
  (Moltiplicazione per i Pesi W)
  (Aggiunta del Bias b)
      |
      V
Output Lineare (z)
  [3.0, 7.0, 2.0] --(3 neuroni/output)
```

### 3. Activation Function (Funzione di Attivazione)

L'output della trasformazione lineare (`z`) passa attraverso una funzione di attivazione (nel nostro caso, ReLU). La funzione ReLU restituisce `max(0, z)` per ciascun elemento, introducendo non-linearità.

#### Dettaglio:
*   **ReLU:** `max(0, z)`

#### Flusso:

```
Output Lineare (z)
 [3.0, 7.0, 2.0]
      |
      V
Funzione di Attivazione (ReLU(z) = a)
      |
      V
Output Attivato (a)
 [3.0, 7.0, 2.0] --(3 output attivati)
```

### Rappresentazione Completa del Flusso

Qui una visione d'insieme del flusso di dati attraverso il singolo layer della rete:

```
+-----------------------+
|      Input Layer (x)  |
|     ([1.0, 2.0])      |
+-----------+-----------+
            |
            V
+-----------------------+
|   Layer Lineare (Wx + b) |
|   (Moltiplicazione con Pesi W) |
|   (Aggiunta Bias b)   |
+-----------+-----------+
            |
            V
+-----------------------+
|    Funzione di Attivazione    |
|       (ReLU(z) = a)   |
+-----------+-----------+
            |
            V
+-----------------------+
|      Output Finale    |
|     ([3.0, 7.0, 2.0]) |
+-----------------------+
```

Questo schema mostra che l'input `x` di 2 features viene trasformato dal layer denso in un output `z` di 3 neuroni, e successivamente attivato dalla funzione ReLU per produrre l'output finale `a` di 3 valori attivati. Ogni freccia rappresenta il passaggio dei dati attraverso una fase della forward propagation.

In [15]:
import tensorflow as tf
import numpy as np

# 1. Definisci un layer Denso (Fully Connected) con Keras
# Useremo un layer con 2 neuroni in input e 3 neuroni in output
# Per la dimostrazione, inizializzeremo i pesi e i bias manualmente
# per rendere l'esempio più prevedibile.

# Crea il layer Dense
dense_layer = tf.keras.layers.Dense(units=3, use_bias=True, activation=None)

# 2. Crea un tensore di input di esempio (batch size 1, 2 features)
input_data = tf.constant([[1.0, 2.0]], dtype=tf.float32) # Usiamo valori interi ma dtype float per compatibilità
print("Input Data (x):\n", input_data.numpy())
print("Shape Input Data:", input_data.shape)

# 3. Il layer viene costruito alla prima chiamata. Eseguiamo una chiamata "dummy" per costruire il layer
# e poter accedere a pesi e bias.
_ = dense_layer(input_data)

# 4. Accedi ai pesi e ai bias del layer dopo che è stato costruito
# Normalmente questi vengono appresi durante l'addestramento, ma per la visualizzazione li impostiamo noi.
manual_weights = tf.constant([[1.0, 0.0, 2.0],
                              [1.0, 3.0, 0.0]], dtype=tf.float32) # (input_features, output_features)
manual_bias = tf.constant([0.0, 1.0, 0.0], dtype=tf.float32) # (output_features,)

dense_layer.set_weights([manual_weights, manual_bias])

weights = dense_layer.get_weights()[0]
bias = dense_layer.get_weights()[1]

print("\n--- Parametri del Layer --- ")
print("Pesi (W):\n", weights)
print("Shape Pesi:", weights.shape)
print("Bias (b):\n", bias)
print("Shape Bias:", bias.shape)

# 5. Esegui la propagazione in avanti passo-passo
print("\n--- Forward Propagation --- ")

# Passo 1: Moltiplicazione Input per Pesi (Wx)
linear_output_before_bias = tf.matmul(input_data, weights)
print("\nOutput Lineare (Wx):\n", linear_output_before_bias.numpy())
print("Shape Output Lineare (Wx):", linear_output_before_bias.shape)

# Passo 2: Aggiunta del Bias (Wx + b)
linear_output = linear_output_before_bias + bias
print("\nOutput Lineare (Wx + b, z):\n", linear_output.numpy())
print("Shape Output Lineare (z):", linear_output.shape)

# Passo 3: Applicazione della Funzione di Attivazione (ad esempio, ReLU)
activation_function = tf.keras.activations.relu
activated_output = activation_function(linear_output)
print("\nOutput Attivato (ReLU(z), a):\n", activated_output.numpy())
print("Shape Output Attivato (a):", activated_output.shape)

print("\n--- Flusso Completo (usando il layer Keras) --- ")
# Questo è come il layer Keras esegue tutto in un colpo:
kera_output = dense_layer(input_data)
relu_keras_output = tf.keras.activations.relu(kera_output)
print("Output del Layer Keras (z):\n", kera_output.numpy())
print("Output Attivato del Layer Keras (a):\n", relu_keras_output.numpy())


Input Data (x):
 [[1. 2.]]
Shape Input Data: (1, 2)

--- Parametri del Layer --- 
Pesi (W):
 [[1. 0. 2.]
 [1. 3. 0.]]
Shape Pesi: (2, 3)
Bias (b):
 [0. 1. 0.]
Shape Bias: (3,)

--- Forward Propagation --- 

Output Lineare (Wx):
 [[3. 6. 2.]]
Shape Output Lineare (Wx): (1, 3)

Output Lineare (Wx + b, z):
 [[3. 7. 2.]]
Shape Output Lineare (z): (1, 3)

Output Attivato (ReLU(z), a):
 [[3. 7. 2.]]
Shape Output Attivato (a): (1, 3)

--- Flusso Completo (usando il layer Keras) --- 
Output del Layer Keras (z):
 [[3. 7. 2.]]
Output Attivato del Layer Keras (a):
 [[3. 7. 2.]]


## Backward Propagation PyTorch (Autograd)

### Subtask:
Aggiungi una cella di codice che mostri come calcolare i gradienti tramite autograd in PyTorch per una semplice funzione di perdita, evidenziando `.backward()` e `.grad`.


Questo codice dimostra la propagazione all'indietro (backward propagation) o differenziazione automatica (autograd) in PyTorch. Questo meccanismo è fondamentale per l'addestramento delle reti neurali, poiché permette di calcolare i gradienti necessari per aggiornare i pesi del modello. Ecco una spiegazione dettagliata:

1) Crea un tensore 'x' con requires_grad=True: Spiega la creazione del tensore x e l'importanza di requires_grad=True per abilitare il tracciamento delle operazioni ai fini del calcolo dei gradienti.
2) Definisci una funzione 'y = x2'**: Descrivi la semplice operazione che trasforma x in y, che è x elevato al quadrato. Menziona come PyTorch tiene traccia di questa operazione.
Definisci una funzione di perdita 'loss = y.sum()': Spiega come y.sum() viene utilizzata come una semplice funzione di perdita (scalarizzazione) per ottenere un singolo valore da cui calcolare il gradiente.

3) Calcola i gradienti con .backward(): Dettaglia il funzionamento di loss.backward(), che innesca il calcolo automatico dei gradienti di loss rispetto a tutti i tensori per cui requires_grad=True era stato impostato (in questo caso, x).

4) Stampa i gradienti di x (x.grad): Spiega come .grad su x restituisce i gradienti calcolati da backward(). Verrà fatto anche un riferimento alla verifica manuale dei gradienti inclusa nei commenti.


**Reasoning**:
I need to add a code cell to demonstrate backward propagation using PyTorch's autograd. This includes creating a tensor with `requires_grad=True`, defining a simple computation and loss, calling `.backward()`, and printing the gradients, as per the subtask instructions.



In [ ]:
import torch

# 1. Crea un tensore 'x' e imposta requires_grad=True per tracciare i gradienti
x = torch.tensor([1.0, 2.0, 3.0], requires_grad=True)
print(f"Tensore di input x: {x}")

# 2. Definisci una semplice funzione: y = x**2
y = x**2
print(f"Output y (x**2): {y}")

# 3. Definisci una funzione di perdita semplice: loss = y.sum()
loss = y.sum()
print(f"Funzione di perdita (y.sum()): {loss}")

# 4. Calcola i gradienti chiamando .backward() sulla perdita
# Questo calcolerà d(loss)/dx per ciascun elemento di x
loss.backward()

# 5. Stampa i gradienti di x (x.grad)
print(f"Gradienti di x (x.grad): {x.grad}")

# Verifichiamo manualmente i gradienti:
# loss = x[0]**2 + x[1]**2 + x[2]**2
# d(loss)/dx[0] = 2*x[0] = 2*1.0 = 2.0
# d(loss)/dx[1] = 2*x[1] = 2*2.0 = 4.0
# d(loss)/dx[2] = 2*x[2] = 2*3.0 = 6.0

## Concatenazione e Stacking PyTorch

### Subtask:
Includi una cella di codice che illustra come concatenare (`torch.cat`) e impilare (`torch.stack`) tensori in PyTorch.


Questo codice illustra come concatenare (torch.cat) e impilare (torch.stack) tensori in PyTorch, operazioni fondamentali per manipolare i dati. Ecco una spiegazione dettagliata:

1) Importazione della libreria PyTorch: Spiegazione della riga che importa la libreria torch.

2) Creazione di tensori di esempio: Dettagli sulla creazione di tensor1, tensor2, tensor3, tensor_cat_col1 e tensor_cat_col2 con torch.randn e le loro forme, evidenziando la loro compatibilità per le diverse operazioni.

3) Concatenazione lungo la dimensione 0 (righe): Spiegazione dell'uso di torch.cat((tensor1, tensor2), dim=0), le condizioni di compatibilità delle dimensioni e come influisce sulla forma del tensore risultante.

4) Concatenazione lungo la dimensione 1 (colonne): Spiegazione dell'uso di torch.cat((tensor_cat_col1, tensor_cat_col2), dim=1), le condizioni di compatibilità (specialmente per le dimensioni non concatenate) e la forma del risultato.

5) Impilamento lungo una nuova dimensione (dim=0): Dettagli sull'uso di torch.stack((tensor1, tensor2), dim=0), sottolineando che torch.stack crea una nuova dimensione, e la forma del tensore impilato.

5) Impilamento lungo una nuova dimensione (dim=1): Spiegazione dell'uso di torch.stack((tensor1, tensor2), dim=1) per impilare lungo una dimensione differente, e la forma risultante.

6) Output e forme dei tensori: Spiegazione dell'uso di print e .shape per visualizzare i tensori risultanti e le loro dimensioni in ogni passaggio chiave.

**Reasoning**:
To fulfill the subtask, I need to add a code cell that imports torch, creates example tensors with compatible dimensions, demonstrates both `torch.cat` along different dimensions and `torch.stack` along a new dimension, and prints the resulting tensors and their shapes, as per the instructions.



In [26]:
import torch

# 1. Crea due tensori PyTorch di esempio
print("\n\n 1 Creazione (torch.randn) di 3 tensori")
print("-"*60)
tensor1 = torch.randn(2, 3) # Tensore di dimensione (2, 3)
tensor2 = torch.randn(2, 3) # Tensore di dimensione (2, 3)
tensor3 = torch.randn(3, 3) # Tensore di dimensione (3, 3) per concatenazione lungo dim=0

print("Tensore 1:\n", tensor1)
print("Tensore 2:\n", tensor2)
print("Tensore 3:\n", tensor3)

# 2. Concatena i tensori lungo la dimensione 0 (righe)
# I tensori devono avere le stesse dimensioni tranne che lungo la dimensione di concatenazione
print("\n\n 2  Concatena (torch.cat) lungo la dim 0 cioè le righe (uno sull'altro)")
print("-"*60)
concatenated_dim0 = torch.cat((tensor1, tensor2), dim=0)
print("\nConcatenazione lungo dim=0 (righe):\n", concatenated_dim0)
print("\nForma dopo concatenazione dim=0:", concatenated_dim0.shape)

# 3. Concatena i tensori lungo la dimensione 1 (colonne)
# I tensori devono avere le stesse dimensioni tranne che lungo la dimensione di concatenazione
# Usiamo tensor1 e tensor3 per dimostrare, tensor3 ha più righe ma le stesse colonne
# NOTA: Per concatenare lungo dim=1, le dimensioni *non* concatenate devono essere le stesse.
# Quindi useremo due nuovi tensori con le righe uguali per questa dimostrazione.
print("\n\n 3 Concatena (torch.cat dim1) lungo la dim 1 cioè le colonne (uno accanto all'altro)")
print("-"*60)
concatenated_dim1 = torch.cat((tensor1, tensor2), dim=1)
print("\nConcatenazione lungo dim=1 (colonne):\n", concatenated_dim1)
print("\nForma dopo concatenazione dim=1:", concatenated_dim1.shape)

# 4. Impila i tensori lungo una nuova dimensione (dim=0)
# I tensori devono avere la stessa dimensione per essere impilati.
print("\n\n 4  Impila (torch.stack dim0) i tensori sulla 3 dimensione (tridimensionale) uno dopo l'altro")
print("-"*60)
stacked_dim0 = torch.stack((tensor1, tensor2), dim=0)
print("\nImpilamento lungo dim=0 (nuova dimensione):\n", stacked_dim0)
print("\nForma dopo impilamento dim=0:", stacked_dim0.shape)

# 5. Impila i tensori lungo una nuova dimensione (dim=1)
# Anche qui, i tensori devono avere la stessa dimensione.
print("\n\n 5 Impila i tensori (torch.stack dim1) sulla 3 dimensione (tridimensionale) uno dopo l'altro ")
print("-"*60)
stacked_dim1 = torch.stack((tensor1, tensor2), dim=1)
print("\nImpilamento lungo dim=1 (nuova dimensione):\n", stacked_dim1)
print("\nForma dopo impilamento dim=1:", stacked_dim1.shape)



 1 Creazione (torch.randn) di 3 tensori
------------------------------------------------------------
Tensore 1:
 tensor([[ 0.2136,  0.2045, -0.6484],
        [ 0.1167, -0.3811,  0.8691]])
Tensore 2:
 tensor([[ 0.2363, -0.3905,  1.7381],
        [-1.8129, -0.9232,  0.2142]])
Tensore 3:
 tensor([[ 0.5595, -0.5102,  0.4872],
        [ 1.0013, -0.8833, -0.6030],
        [ 0.2029, -0.1399, -0.5093]])


 2  Concatena (torch.cat) lungo la dim 0 cioè le righe (uno sull'altro)
------------------------------------------------------------

Concatenazione lungo dim=0 (righe):
 tensor([[ 0.2136,  0.2045, -0.6484],
        [ 0.1167, -0.3811,  0.8691],
        [ 0.2363, -0.3905,  1.7381],
        [-1.8129, -0.9232,  0.2142]])

Forma dopo concatenazione dim=0: torch.Size([4, 3])


 3 Concatena (torch.cat dim1) lungo la dim 1 cioè le colonne (uno accanto all'altro)
------------------------------------------------------------

Concatenazione lungo dim=1 (colonne):
 tensor([[ 0.2136,  0.2045, -0.6484, 

## Operazioni di Riduzione PyTorch

### Subtask:
Aggiungi una cella di codice che dimostri operazioni di riduzione come somma (torch.sum), media (torch.mean) e massimo (torch.max) su tensori PyTorch.


Questo codice dimostra le operazioni di riduzione fondamentali su tensori PyTorch, come la somma, la media e il massimo, sia a livello globale che lungo specifiche dimensioni. Ecco una spiegazione dettagliata:

1) Importazione della libreria PyTorch: Spiegazione della riga che importa la libreria torch.

2) Creazione di un tensore di esempio: Dettagli sulla creazione di tensor_data con torch.randn e la sua forma iniziale (3x4), e la stampa del tensore originale e della sua forma.

3) Calcolo della somma totale: Spiegazione dell'uso di torch.sum(tensor_data) per calcolare la somma di tutti gli elementi del tensore, e la stampa del risultato.

4) Calcolo della somma lungo dimensioni specifiche: Dettagli sull'uso di torch.sum(tensor_data, dim=0) per la somma lungo le colonne e torch.sum(tensor_data, dim=1) per la somma lungo le righe, inclusa la spiegazione delle forme risultanti.

5) Calcolo della media totale: Spiegazione dell'uso di torch.mean(tensor_data) per calcolare la media di tutti gli elementi del tensore, e la stampa del risultato.

6) Calcolo della media lungo dimensioni specifiche: Dettagli sull'uso di torch.mean(tensor_data, dim=0) per la media lungo le colonne e torch.mean(tensor_data, dim=1) per la media lungo le righe, inclusa la spiegazione delle forme risultanti.

7) Calcolo del valore massimo totale: Spiegazione dell'uso di torch.max(tensor_data) per trovare il valore massimo tra tutti gli elementi del tensore, e la stampa del risultato.

8) Calcolo del valore massimo lungo dimensioni specifiche: Dettagli sull'uso di torch.max(tensor_data, dim=0) e torch.max(tensor_data, dim=1) per trovare i valori massimi e i relativi indici lungo le colonne e le righe, inclusa la spiegazione delle forme risultanti per valori e indici.

**Reasoning**:
To fulfill the subtask, I need to add a code cell that imports torch, creates a sample tensor, then applies sum, mean, and max reduction operations globally and along specified dimensions (dim=0 and dim=1), and prints the tensor and the results of each operation along with their shapes, as per the instructions.



In [ ]:
import torch

# 1. Crea un tensore PyTorch di esempio (ad esempio, di dimensione 3x4)
tensor_data = torch.randn(3, 4)
print("Tensore Originale:\n", tensor_data)
print("Forma del Tensore Originale:", tensor_data.shape)

# 2. Calcola la somma di tutti gli elementi del tensore
total_sum = torch.sum(tensor_data)
print("\nSomma totale del tensore:", total_sum.item())

# 3. Calcola la somma lungo la dimensione 0 (righe) e lungo la dimensione 1 (colonne)
sum_dim0 = torch.sum(tensor_data, dim=0)
print("\nSomma lungo la dimensione 0 (colonne):\n", sum_dim0)
print("Forma della somma dim 0:", sum_dim0.shape)

sum_dim1 = torch.sum(tensor_data, dim=1)
print("\nSomma lungo la dimensione 1 (righe):\n", sum_dim1)
print("Forma della somma dim 1:", sum_dim1.shape)

# 4. Calcola la media di tutti gli elementi del tensore
total_mean = torch.mean(tensor_data)
print("\nMedia totale del tensore:", total_mean.item())

# 5. Calcola la media lungo la dimensione 0 e lungo la dimensione 1
mean_dim0 = torch.mean(tensor_data, dim=0)
print("\nMedia lungo la dimensione 0 (colonne):\n", mean_dim0)
print("Forma della media dim 0:", mean_dim0.shape)

mean_dim1 = torch.mean(tensor_data, dim=1)
print("\nMedia lungo la dimensione 1 (righe):\n", mean_dim1)
print("Forma della media dim 1:", mean_dim1.shape)

# 6. Trova il valore massimo di tutti gli elementi del tensore
total_max = torch.max(tensor_data)
print("\nValore massimo totale del tensore:", total_max.item())

# 7. Trova il valore massimo e i relativi indici lungo la dimensione 0 e lungo la dimensione 1
max_dim0 = torch.max(tensor_data, dim=0)
print("\nValore massimo lungo la dimensione 0 (colonne):\n", max_dim0.values)
print("Indici del massimo lungo la dimensione 0:\n", max_dim0.indices)
print("Forma del massimo dim 0:", max_dim0.values.shape)

max_dim1 = torch.max(tensor_data, dim=1)
print("\nValore massimo lungo la dimensione 1 (righe):\n", max_dim1.values)
print("Indici del massimo lungo la dimensione 1:\n", max_dim1.indices)
print("Forma del massimo dim 1:", max_dim1.values.shape)

## Broadcasting TensorFlow

### Subtask:
Aggiungi una cella di codice per dimostrare esempi più complessi di broadcasting con tensori TensorFlow.


Questo codice dimostra esempi più complessi di broadcasting con tensori TensorFlow, mostrando come TensorFlow adatta automaticamente le forme dei tensori per rendere possibili le operazioni. Ecco una spiegazione dettagliata:

1) Importazione della libreria TensorFlow: Spiegazione della riga che importa la libreria tensorflow con l'alias tf.

2) Creazione di 'tensor_a': Dettagli sulla creazione di tensor_a con tf.constant e la sua forma (4, 1, 3), specificando il tipo di dato tf.float32.

3) Creazione di 'tensor_b': Dettagli sulla creazione di tensor_b con tf.constant e la sua forma (1, 5, 3), specificando il tipo di dato tf.float32. Viene evidenziato che le forme di tensor_a e tensor_b sono compatibili per il broadcasting.

4) Addizione con broadcasting (tensor_a + tensor_b): Spiegazione di come TensorFlow estende implicitamente la dimensione 1 di tensor_a da 1 a 5, e la dimensione 0 di tensor_b da 1 a 4, per rendere le forme compatibili per l'addizione. Verrà spiegato che il risultato ha forma (4, 5, 3).
Creazione di 'tensor_c' e 'tensor_d' per un secondo esempio: Dettagli sulla creazione di tensor_c con forma (5, 1) e tensor_d con forma (1, 3) usando tf.random.normal, per dimostrare un altro scenario di broadcasting.

5) Moltiplicazione con broadcasting (tensor_c * tensor_d): Spiegazione di come TensorFlow applica le regole di broadcasting per la moltiplicazione di tensor_c e tensor_d, estendendo le dimensioni appropriate per ottenere un risultato di forma (5, 3).

6) Output dei tensori e delle forme: Spiegazione dell'uso di print per visualizzare i tensori creati, i risultati delle operazioni e le loro dimensioni (.shape) in ogni passaggio.

**Reasoning**:
I need to add a code cell to demonstrate complex TensorFlow broadcasting examples as per the instructions, including creating tensors with specific shapes, performing an operation that leverages broadcasting, and printing the tensors and their shapes.



In [ ]:
import tensorflow as tf

# 1. Crea un tensore di esempio 'tensor_a' con forma (4, 1, 3)
tensor_a = tf.constant([[[1, 2, 3]],
                        [[4, 5, 6]],
                        [[7, 8, 9]],
                        [[10, 11, 12]]], dtype=tf.float32)
print("Tensor A:\n", tensor_a)
print("Forma di Tensor A:", tensor_a.shape)

# 2. Crea un altro tensore di esempio 'tensor_b' con forma compatibile per il broadcasting (1, 5, 3)
tensor_b = tf.constant([[[100, 200, 300],
                         [10, 20, 30],
                         [1, 2, 3],
                         [0.1, 0.2, 0.3],
                         [0, 0, 0]]], dtype=tf.float32)
print("\nTensor B:\n", tensor_b)
print("Forma di Tensor B:", tensor_b.shape)

# 3. Esegui un'operazione che sfrutti il broadcasting (es. addizione)
# TensorFlow "estenderà" la dimensione 1 di tensor_a da 1 a 5
# e la dimensione 0 di tensor_b da 1 a 4.
# Il risultato sarà un tensore di forma (4, 5, 3).
broadcasted_sum = tensor_a + tensor_b

print("\nRisultato dell'addizione con broadcasting (Tensor A + Tensor B):\n", broadcasted_sum)
print("Forma del risultato del broadcasting:", broadcasted_sum.shape)

# Esempio di broadcasting con moltiplicazione
tensor_c = tf.random.normal((5, 1))
tensor_d = tf.random.normal((1, 3))
print("\nTensor C (5,1):\n", tensor_c)
print("Forma di Tensor C:", tensor_c.shape)
print("\nTensor D (1,3):\n", tensor_d)
print("Forma di Tensor D:", tensor_d.shape)

broadcasted_mul = tensor_c * tensor_d
print("\nRisultato della moltiplicazione con broadcasting (Tensor C * Tensor D):\n", broadcasted_mul)
print("Forma del risultato del broadcasting (moltiplicazione):", broadcasted_mul.shape)


## Esempio Layer Denso TensorFlow (Forward)

### Subtask:
Crea una cella di codice con un esempio di forward propagation utilizzando un layer `tf.keras.layers.Dense` e una funzione di attivazione in TensorFlow.


**Reasoning**:
To demonstrate forward propagation in TensorFlow using a Dense layer and an activation function, I will add a code cell that imports the necessary libraries, defines the layers and an input tensor, and then performs the forward pass while printing the shapes at each stage, as per the instructions.



In [ ]:
import tensorflow as tf
from tensorflow.keras import layers

# 1. Definisci un layer Denso
input_features = 10
output_features = 5
dense_layer = layers.Dense(output_features, input_shape=(input_features,))
print(f"Layer Denso: {dense_layer}\n")

# 2. Definisci una funzione di attivazione (es. ReLU)
activation_function = layers.ReLU()
print(f"Funzione di Attivazione: {activation_function}\n")

# 3. Crea un tensore di input di esempio
# Batch di 1 elemento con 10 features
input_tensor = tf.random.normal((1, input_features))
print(f"Tensore di Input:\n{input_tensor}\nShape: {input_tensor.shape}\n")

# 4. Esegui la forward propagation
# Passaggio attraverso il layer denso
output_dense = dense_layer(input_tensor)
print(f"Output dopo il Layer Denso:\n{output_dense}\nShape: {output_dense.shape}\n")

# 5. Passaggio attraverso la funzione di attivazione
output_activated = activation_function(output_dense)
print(f"Output dopo la Funzione di Attivazione (ReLU):\n{output_activated}\nShape: {output_activated.shape}\n")

Questo codice crea un semplice esempio di forward propagation (propagazione in avanti) utilizzando un layer tf.keras.layers.Dense e una funzione di attivazione in TensorFlow. Ecco una spiegazione dettagliata:

1) Importazione delle librerie: Spiegazione delle righe che importano tensorflow e tensorflow.keras.layers, necessarie per la creazione e la gestione dei tensori e dei layer di rete neurale in TensorFlow.

2) Definizione del Layer Denso: Dettagli sulla creazione di un layer denso (layers.Dense) con un numero specifico di neuroni di output. Verrà sottolineato che, a differenza dell'esempio precedente, l'argomento input_shape non è stato specificato per evitare avvisi, e il layer verrà costruito automaticamente alla prima chiamata.

3) Definizione della Funzione di Attivazione: Spiegazione della scelta e della creazione di una funzione di attivazione ReLU (layers.ReLU), che introduce non-linearità nel modello.

4) Creazione del Tensore di Input: Dettagli sulla creazione di un tensore di input di esempio (input_tensor) con tf.random.normal, specificando la sua forma (dimensione del batch e numero di features).

5) Esecuzione della Forward Propagation: Spiegazione dei passaggi sequenziali dell'input attraverso il layer denso e successivamente attraverso la funzione di attivazione, inclusa l'osservazione delle forme dei tensori intermedi e finali. Verrà ribadito che il layer dense_layer si 'costruisce' alla sua prima invocazione con l'input.

6) Output dei tensori e delle forme: Spiegazione dell'uso di print per visualizzare i tensori e le loro dimensioni (.shape) in ogni passaggio chiave del processo di forward propagation.

**Reasoning**:
The previous code generated a UserWarning regarding the `input_shape` argument in `tf.keras.layers.Dense`. To address this, I will remove `input_shape` from the `Dense` layer constructor. The layer will then be built automatically upon its first call, which is a common and accepted practice in TensorFlow and prevents the warning without altering the intended functionality of the forward propagation example.



In [ ]:
import tensorflow as tf
from tensorflow.keras import layers

# 1. Definisci un layer Denso
input_features = 10
output_features = 5
dense_layer = layers.Dense(output_features)
print(f"Layer Denso: {dense_layer}\n")

# 2. Definisci una funzione di attivazione (es. ReLU)
activation_function = layers.ReLU()
print(f"Funzione di Attivazione: {activation_function}\n")

# 3. Crea un tensore di input di esempio
# Batch di 1 elemento con 10 features
input_tensor = tf.random.normal((1, input_features))
print(f"Tensore di Input:\n{input_tensor}\nShape: {input_tensor.shape}\n")

# 4. Esegui la forward propagation
# Passaggio attraverso il layer denso. Il layer verrà costruito alla prima chiamata.
output_dense = dense_layer(input_tensor)
print(f"Output dopo il Layer Denso:\n{output_dense}\nShape: {output_dense.shape}\n")

# 5. Passaggio attraverso la funzione di attivazione
output_activated = activation_function(output_dense)
print(f"Output dopo la Funzione di Attivazione (ReLU):\n{output_activated}\nShape: {output_activated.shape}\n")

## Differenziazione con GradientTape TensorFlow

### Subtask:
Aggiungi una cella di codice per dimostrare la differenziazione automatica di una funzione utilizzando `tf.GradientTape` in TensorFlow.


Questo codice dimostra la differenziazione automatica di una funzione utilizzando tf.GradientTape in TensorFlow, un meccanismo fondamentale per l'addestramento delle reti neurali. Ecco una spiegazione dettagliata:

1) Definizione di una variabile TensorFlow 'x': Spiegazione della creazione della variabile x con tf.Variable e perché è cruciale per il tracciamento automatico dei gradienti in TensorFlow.

2) Utilizzo del blocco tf.GradientTape(): Dettagli sull'uso di with tf.GradientTape() as tape: per registrare tutte le operazioni eseguite al suo interno, che saranno poi utilizzate per calcolare i gradienti.
Definizione della funzione y = x * x:

3) Spiegazione della semplice funzione matematica definita, y come il quadrato di x, e come le operazioni sono monitorate dal GradientTape.

4) Calcolo del gradiente con tape.gradient(): Descrizione di come tape.gradient(y, x) viene utilizzato per calcolare la derivata di y rispetto a x (dy/dx).

5) Stampa del gradiente calcolato: Spiegazione di come accedere e stampare il valore numerico del gradiente calcolato (dy_dx.numpy()), con un riferimento alla verifica manuale inclusa nei commenti.

**Reasoning**:
To demonstrate automatic differentiation using `tf.GradientTape` in TensorFlow, I will add a code cell that initializes a `tf.Variable`, defines a function, and then computes and prints its gradient.



In [ ]:
import tensorflow as tf

# 1. Definisci una variabile TensorFlow 'x'
x = tf.Variable(3.0)
print(f"Variabile x: {x.numpy()}")

# 2. Utilizza un blocco tf.GradientTape() per registrare le operazioni
with tf.GradientTape() as tape:
    # 3. Definisci una funzione y che dipenda da x (es. y = x * x)
    y = x * x
    print(f"Funzione y (x * x): {y.numpy()}")

# 4. Calcola il gradiente di y rispetto a x
dy_dx = tape.gradient(y, x)

# 5. Stampa il gradiente calcolato
print(f"Gradiente di y rispetto a x (dy/dx): {dy_dx.numpy()}")

# Verifichiamo manualmente il gradiente:
# Se y = x^2, allora dy/dx = 2x.
# Per x = 3.0, dy/dx dovrebbe essere 2 * 3.0 = 6.0

## Operazioni Matrice Complesse TensorFlow

### Subtask:
Aggiungi una cella di codice che esplora operazioni matriciali più complesse in TensorFlow, come il prodotto di Hadamard (elemento per elemento) e l'inversione di matrici (se applicabile).


Questo codice esplora operazioni matriciali più complesse in TensorFlow, come il prodotto di Hadamard (moltiplicazione elemento per elemento) e l'inversione di matrici. Ecco una spiegazione dettagliata:

1) Importazione della libreria TensorFlow: Spiegazione della riga che importa la libreria tensorflow con l'alias tf.

2) Prodotto di Hadamard (Moltiplicazione elemento per elemento): Dettagli sulla creazione di due tensori di esempio (tensor_hadamard_a e tensor_hadamard_b) e come l'operatore * esegue il prodotto di Hadamard, stampando i tensori e il risultato con le loro forme.
3) Inversione di Matrici: Spiegazione della creazione di una matrice invertibile (matrix_to_invert) e l'uso di tf.linalg.inv per calcolarne l'inversa. Verrà mostrato come verificare l'inversione moltiplicando la matrice originale per la sua inversa per ottenere una matrice identità.

4) Gestione degli errori per matrici non invertibili: Dimostrazione di come un blocco try-except gestisce l'errore tf.errors.InvalidArgumentError quando si tenta di invertire una matrice singolare (non invertibile), come quella con determinante nullo.

5) Output dei tensori e delle forme: Spiegazione dell'uso di print per visualizzare i tensori creati, i risultati delle operazioni e le loro dimensioni (.shape) in ogni passaggio.

**Reasoning**:
To fulfill the subtask, I need to add a code cell that demonstrates Hadamard product and matrix inversion in TensorFlow. This includes importing TensorFlow, creating example tensors, performing element-wise multiplication, attempting matrix inversion, and verifying the result with a try-except block for non-invertible matrices.



In [ ]:
import tensorflow as tf

# 1. Prodotto di Hadamard (Element-wise multiplication)
print("--- Prodotto di Hadamard ---")
# Crea due tensori di esempio di uguale dimensione (es. 3x3)
tensor_hadamard_a = tf.constant([[1, 2, 3],
                               [4, 5, 6],
                               [7, 8, 9]], dtype=tf.float32)
tensor_hadamard_b = tf.constant([[10, 20, 30],
                               [40, 50, 60],
                               [70, 80, 90]], dtype=tf.float32)

print("Tensor Hadamard A:\n", tensor_hadamard_a.numpy())
print("Forma di Tensor Hadamard A:", tensor_hadamard_a.shape)
print("Tensor Hadamard B:\n", tensor_hadamard_b.numpy())
print("Forma di Tensor Hadamard B:", tensor_hadamard_b.shape)

# Calcola il prodotto di Hadamard (moltiplicazione elemento per elemento)
hadamard_product = tensor_hadamard_a * tensor_hadamard_b

print("\nRisultato del Prodotto di Hadamard (A * B):\n", hadamard_product.numpy())
print("Forma del Prodotto di Hadamard:", hadamard_product.shape)

# 2. Inversione di Matrici
print("\n--- Inversione di Matrici ---")

# Crea un tensore quadrato invertibile (es. 3x3)
# Usiamo tf.eye(3) per una matrice invertibile semplice e poi la modifichiamo leggermente
matrix_to_invert = tf.constant([[1.0, 2.0, 3.0],
                                [0.0, 1.0, 4.0],
                                [5.0, 6.0, 0.0]], dtype=tf.float32)

print("Matrice Originale per Inversione:\n", matrix_to_invert.numpy())
print("Forma della Matrice Originale:", matrix_to_invert.shape)

try:
    # Calcola l'inversa della matrice
    matrix_inverse = tf.linalg.inv(matrix_to_invert)
    print("\nMatrice Inversa:\n", matrix_inverse.numpy())
    print("Forma della Matrice Inversa:", matrix_inverse.shape)

    # Verifica moltiplicando la matrice originale per la sua inversa
    identity_check = tf.matmul(matrix_to_invert, matrix_inverse)
    print("\nVerifica (Matrice Originale @ Matrice Inversa):\n", identity_check.numpy())
    # Le differenze minime sono dovute a imprecisioni in virgola mobile, quindi verifichiamo la vicinanza all'identità
    is_identity = tf.reduce_all(tf.abs(identity_check - tf.eye(matrix_to_invert.shape[0])) < 1e-4)
    print(f"Il prodotto è una matrice identità (entro una piccola tolleranza): {is_identity.numpy()}")

except tf.errors.InvalidArgumentError as e:
    print(f"\nErrore durante l'inversione della matrice: {e}")
    print("La matrice potrebbe non essere invertibile (es. determinante nullo).")

# Esempio di matrice non invertibile per dimostrare l'errore
print("\n--- Esempio con Matrice Non Invertibile ---")
non_invertible_matrix = tf.constant([[1.0, 2.0],
                                     [2.0, 4.0]], dtype=tf.float32) # Determinante = 1*4 - 2*2 = 0
print("Matrice Non Invertibile:\n", non_invertible_matrix.numpy())

try:
    tf.linalg.inv(non_invertible_matrix)
except tf.errors.InvalidArgumentError as e:
    print(f"Errore atteso per matrice non invertibile: {e}")


## Final Task

### Subtask:
Rivedi e finalizza le celle aggiunte, assicurandoti che siano ben commentate e pertinenti al contesto di un corso di deep learning.


## Summary:

### Data Analysis Key Findings

The analysis involved demonstrating fundamental and advanced tensor operations in both PyTorch and TensorFlow, crucial for deep learning model development.

*   **PyTorch Tensor Operations:**
    *   **Matrix Multiplication and Element-wise Operations:** Basic matrix multiplication (`torch.matmul`) of (2,3) and (3,4) tensors resulted in a (2,4) tensor. Element-wise multiplication of (2,3) tensors produced a (2,3) tensor.
    *   **Broadcasting:** Successfully applied scalar broadcasting (e.g., (2,3) tensor multiplied by a scalar resulted in a (2,3) tensor) and tensor broadcasting (e.g., (2,3) tensor multiplied by a (1,3) tensor resulted in a (2,3) tensor).
    *   **Reshaping and Transposition:** Tensors were reshaped from (2,3) to (3,2) and (6,). Transposition using both `.T` and `torch.transpose` correctly changed a (2,3) tensor to a (3,2) tensor.
    *   **Forward Propagation:** A simple forward pass through a `nn.Linear` layer (10 input features, 5 output features) followed by a `nn.ReLU` activation transformed an input tensor from shape (1,10) to (1,5).
    *   **Backward Propagation (Autograd):** Demonstrated automatic differentiation for `y = x^2` where $x = [1, 2, 3]$. The computed gradients $x.\text{grad}$ were $[2, 4, 6]$, matching the analytical derivative $2x$.
    *   **Concatenation and Stacking:** `torch.cat` demonstrated concatenation along `dim=0` (two (2,3) tensors yielded a (4,3) tensor) and `dim=1` (a (2,2) and a (2,3) tensor yielded a (2,5) tensor). `torch.stack` (two (2,3) tensors) created a new dimension, resulting in a (2,2,3) tensor when stacked along `dim=0` or `dim=1`.
    *   **Reduction Operations:** `torch.sum`, `torch.mean`, and `torch.max` were applied globally and along specific dimensions for a 3x4 tensor. For example, summing along `dim=0` resulted in a (4,) shaped tensor, and along `dim=1` resulted in a (3,) shaped tensor.

*   **TensorFlow Tensor Operations:**
    *   **Complex Broadcasting:** Illustrated advanced broadcasting rules, where a (4,1,3) tensor added to a (1,5,3) tensor resulted in a (4,5,3) tensor. Similarly, a (5,1) tensor multiplied by a (1,3) tensor yielded a (5,3) tensor.
    *   **Forward Propagation (`tf.keras.layers.Dense`):** A forward pass through a `tf.keras.layers.Dense` layer (10 input features, 5 output features) with a `tf.keras.layers.ReLU` activation transformed an input tensor from shape (1,10) to (1,5), similar to PyTorch's linear layer.
    *   **Automatic Differentiation (`tf.GradientTape`):** Demonstrated gradient computation for `y = x^2` with $x=3.0$ using `tf.GradientTape`, correctly yielding a gradient of $6.0$.
    *   **Complex Matrix Operations:** Successfully performed Hadamard product (element-wise multiplication) on two 3x3 tensors. Matrix inversion using `tf.linalg.inv` was demonstrated and verified, including robust error handling for non-invertible matrices.

### Insights or Next Steps

*   The demonstrations effectively cover core tensor manipulations, linear algebra operations, and the foundations of automatic differentiation in both PyTorch and TensorFlow, providing a solid base for understanding deep learning mechanics.
*   Future steps could involve exploring more advanced tensor operations (e.g., SVD, FFT), implementing basic neural network architectures (e.g., CNN, RNN layers), or demonstrating distributed training concepts within these frameworks.
